### ISSUE TITLE
How do I generate the caricature versions of my sample images?

### ISSUE THREAD

**Issue by marcthegreat0847** [Juyong/CaricatureFace#15]

**Comment by RainbowRui** [comment]
If you want to generate the caricature versions of sampled normal images, we are sorry to tell you our method could not do that. Maybe you can follow other methods, such as CariGAN.
If you want to create the ground-truth 3D caricature of your sample caricatures, we are sorry to tell you it could not generate more 3D caricatures by your own. Since we use other people's method to construct the ground-truth 3D caricatures, and they do not make their method open.

**Comment by marcthegreat0847** [comment]
Oh, I see. Thank you for your response!
