### ISSUE TITLE
animation of mesh

### ISSUE THREAD

**Issue by oferidan1** [Juyong/CaricatureFace#44]
Hello, 
thanks for sharing this great paper and code.
I have a question: is it possible to do animation of the mesh output? 
for example, BFM basis enables animation using manipulating of expressions.
is it possible to achieve this effect over the this model? if so, how?
Thanks,
Ofer

**Comment by RainbowRui** [comment]
Hello,
thanks for pointing this out.
We do not consider caricature animation in this work, which is a nice problem. 
You could follow some other works for caricature amination. Or use 3D landmarks to guide deform 3D recovered mesh.
Thanks,
Hongrui

**Comment by oferidan1** [comment]
Hi Hongrui,
Thanks for your quick reply.
Let me clarify my question: when using BFM 3dmm model, one can manipulate the output expression (smile, eye close, etc) by updating the expression coefficients. 
So, is there away to do something similar with your model? 
For example, if we would use BFM model as initial basis instead of face warehouse (or add the expression to face warehouse basis), would the expression manipulation still work?
Thanks,
Ofer

**Comment by RainbowRui** [comment]
Hi Ofer,
Our work do not consider this editing mode. It needs to define and parameterize expressions on caricature data, which we do not consider. So if you need to animate with our model, maybe you could consider interpolate the estimated deformation coefficients (but it may interpolate both identities and expressions bewteen two input caricatures).
If you use BFM model instead of FaceWarehouse, our model is also based on deformation representation (non-linear parameterization) but not linear parameterization (like 3DMM). So it is still hard to interpolate expressions merely.
Thanks,
Hongrui

**Comment by oferidan1** [comment]
Ok, I understand.
Thanks for the clarification.
Ofer

**Comment by RainbowRui** [comment]
You are welcome.
Hongrui
